### ISSUE TITLE
don't single-line annotations

### ISSUE THREAD

**Issue by IgorMinar** [angular/clang-format#19]
clang-format insists that: 

```
@Component({
  selector: 'inbox-detail'
})
```

should be formatted as:

```
@Component({selector: 'inbox-detail'})
```

which is not cool because it results in weird looking code when other annotations are present on the same class:

```
@Component({selector: 'inbox-app'})
@View({
   // <a router-link=\"gamePage\" [router-params]=\"{'id':3}\">ddd</a>  
   templateUrl: "inbox-app.html",
})
class DraftsCmp {
...
}
```

Additionally single-lining an annotation with multiple properties causes readability issues

```
@View({templateUrl: "drafts.html", directives: [NgFor, RouterLink]})
```

Maybe the solution is to just turn of single-lining for object literals?

**Comment by mprobst** [comment]
Not sure I agree. I really like collapsing object literals, in most code it's a big readability/scanability improvement; also it safes precious vertical whitespace.

I think the wrap here is a bit of a waste of space, and rather interrupts the reading of `this is a @Component with a selector of 'inbox-detail'`.

Note if you explicitly want to force an object literal onto multiple lines (e.g. because you think you'll keep adding to it), you can easily do that by having a trailing comma in it:

``` ts
@Component({
  selector: 'inbox-detail',
})
```

**Comment by vicb** [comment]
I'm with Martin on this one

**Comment by Foxandxss** [comment]
I am with Igor.

We are using clang-format for ng-bootstrap and I don't really like what it does with the annotations. We have clang set to 120 columns and lots of our annotations are one-liner now.

**Comment by mprobst** [comment]
@Foxandxss put a trailing comma in any object literal or array literal, and it will format one per line, see my example above.

Also, setting column width to 120 and then complaining that columns are too wide is no fair! ;-)

**Comment by Foxandxss** [comment]
Oh, I see now. Will propose the idea to the others.

About 120, It wasn't my petition :P

**Comment by IgorMinar** [comment]
I prefer code style that is refactoring-friendly. That means, if I need to add or remove a small bit of code, it should create a huge diff in the patch.

Adding trailing comma is an option and makes refactoring even easier.

I do feel pretty strongly about multi-property metadata decorators. Those should never be single lined because scanning that code is impossible.

**Comment by mprobst** [comment]
So if you don't have the trailing comma, you'll create a change on that line anyway when you change something. If you do have the trailing comma, you get formatting with one per line. So that fixes the issue, right?

I think it might be possible to special case object literals in `@Annotations`, but it'd be a bit tricky.

**Comment by IgorMinar** [comment]
I guess so, but I'm sure that some people will find this behavior confusing.

**Comment by mprobst** [comment]
Closing, this doesn't seem to be such a big deal.
